// -------------------------------------------------------------
// 
// File Name: D:\Desktop\2024_E_Design\2023C\matlab\hdlsrc\signalSim\Cnt_sin2cos_L.v
// Created: 2024-07-19 14:33:43
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-06
// Target subsystem base rate: 1e-06
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1e-06
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// CntOutPhaseShift              ce_out        1e-06
// CntOut                        ce_out        1e-06
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Cnt_sin2cos_L
// Source Path: signalSim/Cnt_sin2cos_L
// Hierarchy Level: 0
// Model version: 1.10
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Cnt_sin2cos_L
          (clk,
           reset,
           clk_enable,
           ce_out,
           CntOutPhaseShift,
           CntOut);


  input   clk;
  input   reset;
  input   clk_enable;
  output  ce_out;
  output  [9:0] CntOutPhaseShift;  // ufix10
  output  [9:0] CntOut;  // ufix10


  wire enb;
  wire HDL_Counter_ctrl_const_out;
  reg  HDL_Counter_ctrl_delay_out;
  wire [9:0] HDL_Counter_Initial_Val_out;  // ufix10
  wire [9:0] count_step;  // ufix10
  wire [9:0] count_from;  // ufix10
  wire [9:0] HDL_Counter_out1;  // ufix10
  wire [9:0] count;  // ufix10
  wire need_to_wrap;
  wire [9:0] count_value;  // ufix10
  reg [9:0] HDL_Counter_out;  // ufix10
  wire HDL_Counter1_ctrl_const_out;
  reg  HDL_Counter1_ctrl_delay_out;
  wire [9:0] HDL_Counter1_Initial_Val_out;  // ufix10
  wire [9:0] count_step_1;  // ufix10
  wire [9:0] count_from_1;  // ufix10
  wire [9:0] HDL_Counter1_out1;  // ufix10
  wire [9:0] count_1;  // ufix10
  wire need_to_wrap_1;
  wire [9:0] count_value_1;  // ufix10
  reg [9:0] HDL_Counter1_out;  // ufix10


  assign HDL_Counter_ctrl_const_out = 1'b1;



  assign enb = clk_enable;

  always @(posedge clk)
    begin : HDL_Counter_ctrl_delay_process
      if (reset == 1'b0) begin
        HDL_Counter_ctrl_delay_out <= 1'b0;
      end
      else begin
        if (enb) begin
          HDL_Counter_ctrl_delay_out <= HDL_Counter_ctrl_const_out;
        end
      end
    end



  assign HDL_Counter_Initial_Val_out = 10'b0000000101;



  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 1000
  assign count_step = 10'b0000000001;



  assign count_from = 10'b0000000001;



  assign count = HDL_Counter_out1 + count_step;



  assign need_to_wrap = HDL_Counter_out1 == 10'b1111101000;



  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);



  always @(posedge clk)
    begin : HDL_Counter_process
      if (reset == 1'b0) begin
        HDL_Counter_out <= 10'b0000000000;
      end
      else begin
        if (enb) begin
          HDL_Counter_out <= count_value;
        end
      end
    end



  assign HDL_Counter_out1 = (HDL_Counter_ctrl_delay_out == 1'b0 ? HDL_Counter_Initial_Val_out :
              HDL_Counter_out);



  assign CntOutPhaseShift = HDL_Counter_out1;

  assign HDL_Counter1_ctrl_const_out = 1'b1;



  always @(posedge clk)
    begin : HDL_Counter1_ctrl_delay_process
      if (reset == 1'b0) begin
        HDL_Counter1_ctrl_delay_out <= 1'b0;
      end
      else begin
        if (enb) begin
          HDL_Counter1_ctrl_delay_out <= HDL_Counter1_ctrl_const_out;
        end
      end
    end



  assign HDL_Counter1_Initial_Val_out = 10'b0000000001;



  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 1000
  assign count_step_1 = 10'b0000000001;



  assign count_from_1 = 10'b0000000001;



  assign count_1 = HDL_Counter1_out1 + count_step_1;



  assign need_to_wrap_1 = HDL_Counter1_out1 == 10'b1111101000;



  assign count_value_1 = (need_to_wrap_1 == 1'b0 ? count_1 :
              count_from_1);



  always @(posedge clk)
    begin : HDL_Counter1_process
      if (reset == 1'b0) begin
        HDL_Counter1_out <= 10'b0000000000;
      end
      else begin
        if (enb) begin
          HDL_Counter1_out <= count_value_1;
        end
      end
    end



  assign HDL_Counter1_out1 = (HDL_Counter1_ctrl_delay_out == 1'b0 ? HDL_Counter1_Initial_Val_out :
              HDL_Counter1_out);



  assign CntOut = HDL_Counter1_out1;

  assign ce_out = clk_enable;

endmodule  // Cnt_sin2cos_L

