// -------------------------------------------------------------
// 
// File Name: D:\Desktop\2024_E_Design\2023C\matlab\hdlsrc\signalSim\DualRam.v
// Created: 2024-07-19 10:35:05
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-06
// Target subsystem base rate: 1e-06
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1e-06
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// wr_dout                       ce_out        1e-06
// rd_dout                       ce_out        1e-06
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DualRam
// Source Path: signalSim/DualRam
// Hierarchy Level: 0
// Model version: 1.9
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DualRam
          (clk,
           clk_enable,
           wr_din,
           wr_addr,
           wr_en,
           rd_addr,
           ce_out,
           wr_dout,
           rd_dout);


  input   clk;
  input   clk_enable;
  input   [7:0] wr_din;  // uint8
  input   [9:0] wr_addr;  // ufix10
  input   wr_en;
  input   [9:0] rd_addr;  // ufix10
  output  ce_out;
  output  [7:0] wr_dout;  // uint8
  output  [7:0] rd_dout;  // uint8


  wire [7:0] Dual_Port_RAM_out1;  // uint8
  wire [7:0] Dual_Port_RAM_out2;  // uint8


  DualPortRAM_generic #(.AddrWidth(10),
                        .DataWidth(8)
                        )
                      u_Dual_Port_RAM (.clk(clk),
                                       .enb(clk_enable),
                                       .wr_din(wr_din),
                                       .wr_addr(wr_addr),
                                       .wr_en(wr_en),
                                       .rd_addr(rd_addr),
                                       .wr_dout(Dual_Port_RAM_out1),
                                       .rd_dout(Dual_Port_RAM_out2)
                                       );

  assign wr_dout = Dual_Port_RAM_out1;

  assign rd_dout = Dual_Port_RAM_out2;

  assign ce_out = clk_enable;

endmodule  // DualRam

