// -------------------------------------------------------------
// 
// File Name: D:\Desktop\2024_E_Design\2023C\matlab\hdlsrc\signalSim\Dual_Port_RAM_System1.v
// Created: 2024-07-19 09:51:33
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-06
// Target subsystem base rate: 1e-06
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1e-06
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Wr_Out                        ce_out        1e-06
// Rd_Out                        ce_out        1e-06
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Dual_Port_RAM_System1
// Source Path: signalSim/Dual_Port_RAM_System1
// Hierarchy Level: 0
// Model version: 1.9
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Dual_Port_RAM_System1
          (clk,
           clk_enable,
           DataIn,
           Wr_Addr,
           Wr_En,
           Rd_Addr,
           ce_out,
           Wr_Out,
           Rd_Out);


  input   clk;
  input   clk_enable;
  input   signed [7:0] DataIn;  // int8
  input   [15:0] Wr_Addr;  // uint16
  input   Wr_En;
  input   [15:0] Rd_Addr;  // uint16
  output  ce_out;
  output  signed [7:0] Wr_Out;  // int8
  output  signed [7:0] Rd_Out;  // int8


  wire signed [7:0] Dual_Port_RAM_out1;  // int8
  wire signed [7:0] Dual_Port_RAM_out2;  // int8


  DualPortRAM_generic #(.AddrWidth(16),
                        .DataWidth(8)
                        )
                      u_Dual_Port_RAM (.clk(clk),
                                       .enb(clk_enable),
                                       .wr_din(DataIn),
                                       .wr_addr(Wr_Addr),
                                       .wr_en(Wr_En),
                                       .rd_addr(Rd_Addr),
                                       .wr_dout(Dual_Port_RAM_out1),
                                       .rd_dout(Dual_Port_RAM_out2)
                                       );

  assign Wr_Out = Dual_Port_RAM_out1;

  assign Rd_Out = Dual_Port_RAM_out2;

  assign ce_out = clk_enable;

endmodule  // Dual_Port_RAM_System1

