// -------------------------------------------------------------
// 
// File Name: D:\Desktop\2024_E_Design\2023C\matlab\hdlsrc\signalSim\NCO.v
// Created: 2024-07-19 21:25:07
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 5e-08
// Target subsystem base rate: 5e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        5e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Sin                           ce_out        5e-08
// ValidOut                      ce_out        5e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: NCO
// Source Path: signalSim/NCO
// Hierarchy Level: 0
// Model version: 1.10
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module NCO
          (clk,
           reset,
           clk_enable,
           Inc,
           ValidIn,
           ce_out,
           Sin,
           ValidOut);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [31:0] Inc;  // uint32
  input   ValidIn;
  output  ce_out;
  output  signed [11:0] Sin;  // sfix12_En10
  output  ValidOut;


  wire signed [11:0] NCO1_out1;  // sfix12_En10
  wire NCO1_out2;


  NCO1 u_NCO1 (.clk(clk),
               .reset(reset),
               .enb(clk_enable),
               .inc(Inc),  // uint32
               .validIn(ValidIn),
               .sine(NCO1_out1),  // sfix12_En10
               .validOut(NCO1_out2)
               );

  assign Sin = NCO1_out1;

  assign ValidOut = NCO1_out2;

  assign ce_out = clk_enable;

endmodule  // NCO

