// -------------------------------------------------------------
// 
// File Name: D:\Desktop\2024_E_Design\2023C\matlab\hdlsrc\signalSim\NCO1.v
// Created: 2024-07-19 21:25:07
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: NCO1
// Source Path: signalSim/NCO/NCO1
// Hierarchy Level: 1
// Model version: 1.10
// 
// NCO
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module NCO1
          (clk,
           reset,
           enb,
           inc,
           validIn,
           sine,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] inc;  // uint32
  input   validIn;
  output  signed [11:0] sine;  // sfix12_En10
  output  validOut;


  reg  [4:0] outsel_reg_reg;  // ufix1 [5]
  wire outsel;
  wire signed [11:0] outzero;  // sfix12_En10
  wire signed [30:0] const0;  // sfix31
  wire signed [30:0] pInc;  // sfix31
  wire signed [30:0] validPInc;  // sfix31
  reg signed [30:0] accphase_reg;  // sfix31
  wire signed [30:0] addpInc;  // sfix31
  wire signed [30:0] pOffset;  // sfix31
  wire signed [30:0] accoffset;  // sfix31
  reg signed [30:0] accoffsete_reg;  // sfix31
  wire [3:0] dither;  // ufix4
  wire signed [30:0] casteddither;  // sfix31
  reg signed [30:0] dither_reg;  // sfix31
  wire signed [30:0] accumulator;  // sfix31
  wire [11:0] accQuantized;  // ufix12_E19
  wire signed [11:0] outs;  // sfix12_En10
  wire signed [11:0] validouts;  // sfix12_En10
  reg signed [11:0] sine_1;  // sfix12_En10
  reg  validOut_1;


  always @(posedge clk)
    begin : outsel_reg_process
      if (reset == 1'b0) begin
        outsel_reg_reg <= {5{1'b0}};
      end
      else begin
        if (enb) begin
          outsel_reg_reg[0] <= validIn;
          outsel_reg_reg[32'sd4:32'sd1] <= outsel_reg_reg[32'sd3:32'sd0];
        end
      end
    end

  assign outsel = outsel_reg_reg[4];



  assign outzero = 12'sb000000000000;



  // Constant Zero
  assign const0 = 31'sb0000000000000000000000000000000;



  assign pInc = $signed(inc[30:0]);



  assign validPInc = (validIn == 1'b0 ? const0 :
              pInc);



  // Add phase increment
  assign addpInc = accphase_reg + validPInc;



  // Phase increment accumulator register
  always @(posedge clk)
    begin : AccPhaseRegister_process
      if (reset == 1'b0) begin
        accphase_reg <= 31'sb0000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          accphase_reg <= addpInc;
        end
      end
    end



  assign pOffset = 31'sb0000000000000000000000000000000;



  // Add phase offset
  assign accoffset = accphase_reg + pOffset;



  // Phase offset accumulator register
  always @(posedge clk)
    begin : AccOffsetRegister_process
      if (reset == 1'b0) begin
        accoffsete_reg <= 31'sb0000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          accoffsete_reg <= accoffset;
        end
      end
    end



  DitherGen u_dither_inst (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .validIn(validIn),
                           .dither(dither)  // ufix4
                           );

  assign casteddither = {27'b0, dither};



  // Dither input register
  always @(posedge clk)
    begin : DitherRegister_process
      if (reset == 1'b0) begin
        dither_reg <= 31'sb0000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          dither_reg <= casteddither;
        end
      end
    end



  // Add dither
  assign accumulator = accoffsete_reg + dither_reg;



  // Phase quantization
  assign accQuantized = accumulator[30:19];



  WaveformGen u_Wave_inst (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .phaseIdx(accQuantized),  // ufix12_E19
                           .sine(outs)  // sfix12_En10
                           );

  assign validouts = (outsel == 1'b0 ? outzero :
              outs);



  // Output register
  always @(posedge clk)
    begin : OutputRegister_process
      if (reset == 1'b0) begin
        sine_1 <= 12'sb000000000000;
      end
      else begin
        if (enb) begin
          sine_1 <= validouts;
        end
      end
    end



  // validOut register
  always @(posedge clk)
    begin : validOut_reg_process
      if (reset == 1'b0) begin
        validOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          validOut_1 <= outsel;
        end
      end
    end



  assign sine = sine_1;

  assign validOut = validOut_1;

endmodule  // NCO1

